exports.document = document if window?
exports.request = jQuery.ajax if jQuery?
exports.Events = require('./wingman/events')
exports.Module = require('./wingman/module')
exports.Object = require('./wingman/object')
exports.Template = require('./wingman/template')
exports.View = require('./wingman/view')
exports.Model = require('./wingman/model')
exports.Controller = class
exports.App = require('./wingman/app')
